/* Generated by Opal 0.7.0.dev */
(function($opal) {
  $opal.dynamic_require_severity = "error";
  var self = $opal.top, $scope = $opal, nil = $opal.nil, $breaker = $opal.breaker, $slice = $opal.slice, $module = $opal.module;

  $opal.add_stubs(['$include']);
  (function($base) {
    var self = $module($base, 'Yeah');

    var def = self._proto, $scope = self._scope;

    self.$include($scope.get('Web'))
    
  })(self);
  return self.$include($scope.get('Yeah'));
})(Opal);

//# sourceMappingURL=yeah/web/setup.map
;
