/* Generated by Opal 0.7.0.dev */
(function($opal) {
  $opal.dynamic_require_severity = "error";
  var self = $opal.top, $scope = $opal, nil = $opal.nil, $breaker = $opal.breaker, $slice = $opal.slice;

  $opal.add_stubs(['$new', '$default']);
  return $scope.get('Game').$default().$new()
})(Opal);

//# sourceMappingURL=yeah/web/start.map
;
